# Generated by Django 2.2.5 on 2020-11-08 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_size', models.BigIntegerField(null=True, verbose_name='画像サイズ')),
                ('image_origin_name', models.CharField(max_length=50, null=True, verbose_name='画像元名')),
                ('image_extension', models.CharField(max_length=10, null=True, verbose_name='画像拡張子')),
                ('reg_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
            ],
            options={
                'db_table': 'post_iamge',
            },
        ),
    ]
